exclude: ".git"
default_stages:
    - commit
fail_fast: true

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
        args: ['--unsafe']
    -   id: check-toml
    -   id: check-merge-conflict
    -   id: check-added-large-files

-   repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
    -   id: black

-   repo: https://github.com/timothycrosley/isort
    rev: 5.13.2
    hooks:
    -   id: isort
        args: ["--profile", "black"]

-   repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-isort]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
    -   id: mypy


# run local pylint in venv
-   repo: local
    hooks:
    -   id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        require_serial: true
        args:
        - --max-line-length=120
        - --ignore-imports=yes
        - -d duplicate-code
        - -d C0111,W0621,R0913,R1705,W0201,R0903


-   repo: https://github.com/asottile/pyupgrade
    rev: v3.15.2
    hooks:
    -   id: pyupgrade
